### ISSUE TITLE
Use SecureRandom instead of java.util.Random

### ISSUE THREAD

**Issue by saidone75** [Bardia95/programming-bitcoin#1]
Not really an issue, but as from javadoc "_Instances of java.util.Random are not cryptographically secure. Consider instead using SecureRandom to get a cryptographically secure pseudo-random number generator for use by security-sensitive applications_"

**Comment by Bardia95** [comment]
I am only using that function to test primality, I’m not using it for the random number generation for the cryptography

**Comment by saidone75** [comment]
Let me say I don't think it's a good idea anyway ;-)
