### ISSUE TITLE
BigInteger probablePrime

### ISSUE THREAD

**Issue by saidone75** [Bardia95/programming-bitcoin#2]
Since you are already importing BigInteger, if you want reduce boilerplate there's a neat method for big primes:
```
public static BigInteger probablePrime(int bitLength,
                       Random rnd)
```
I think it use a Miller-Rabin test but I'm not 100% sure.
[probablePrime](https://docs.oracle.com/javase/7/docs/api/java/math/BigInteger.html#probablePrime(int,%20java.util.Random))

**Comment by Bardia95** [comment]
In my first post I go over how to test primality so that’s why I have the boiler plate in there
